apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodeselector
  name: nodeselector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeselector
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodeselector
    spec:
      containers:
      - image: docker.io/dineshverma877/netflix_clone
        name: netflix-clone-4mr6r
      nodeSelector:
        disk: hdd
status: {}
