apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodename
  name: nodename
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodename
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodename
    spec:
      containers:
      - image: docker.io/dineshverma877/netflix_clone
        name: neflix-clone-dqz9c
      nodeName: controlplane   
status: {}
